<?xml version="1.0" encoding="utf-8"?><Database Name="Students_DB" Class="StudentsDBDataClassesDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=mihir\sqlexpress;Initial Catalog=Students_DB;Integrated Security=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="Students_DBConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Students" Member="Students">
    <Type Name="Student">
      <Column Name="Student_Name" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Student_Age" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Student_University" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Student_Id" Type="System.String" DbType="NChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
    </Type>
  </Table>
</Database>